### ISSUE TITLE
getPropertyValue returns empty string instead of 'none'

### ISSUE THREAD

**Issue by peebeebee** [rmarganti/re-position#13]
Line:
https://github.com/rmarganti/re-position/blob/a8bfead0227b83edbef2f32b2142f028e1196b06/src/utils/dom.ts#L99

Documentation:
https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/getPropertyValue

Be aware that the behaviour could've been different in the past, since I also found changes in the following behaviour: https://www.fxsitecompat.com/en-CA/docs/2018/getcomputedstyle-no-longer-returns-null-when-style-can-t-be-retrieved/

**Comment by rmarganti** [comment]
This is fixed here:
https://github.com/rmarganti/re-position/pull/14

Will likely push a patch version in the near future.
