### ISSUE TITLE
Snap should be consistent across groups

### ISSUE THREAD

**Issue by jide** [rmarganti/re-position#9]
When using snapTo, if items are placed at uneven positions, dragging groups won't snap all items at the same time.

I'm too unfamiliar with observables to think about a fix but would love to see how this can be fixed, looking at the code it seems it should work to me.

**Comment by rmarganti** [comment]
This has been updated in 0.4.1.

As of now, the element who is being interacted with via the mouse will snap, with all other elements in the group "following along." In the future, I would like the whole group to snap as if it were one giant element. However, this is going to require a larger rewrite (which will also support rotating and resizing grouped elements as one).

**Comment by jide** [comment]
Awesome. If you're going to rewrite the snap part and grouping, allowing passing a function to snapTo would be a great addition. I had this need to make elements snap to each others. I use a workaround for this but if it existed as a feature it would be easier.
